---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "lua",
      "vim",
      "bash",
      "c",
      "css",
      "dockerfile",
      "dot",
      "go",
      "gomod",
      "html",
      "javascript",
      "json",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "requirements",
      "sql",
      "svelte",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "vimdoc",
      "yaml",
    },
  },
}
